apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: procurement-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ogash3103/Unit-3-Advanced-Software-Design-and-Architecture.git
    targetRevision: main
    path: AgriProcurementPlatform/deploy/charts/procurement-api
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: procurement
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
